// Chuỗi hiển thị cho người dùng, tập trung một nơi để rà soát câu chữ trung thực.

export const copy = {
  hoursEstimateDisclaimer: 'Số giờ học là ước tính, có thể lệch so với thực tế của bạn.',
  priceReferenceLabel: (checkedAtIso: string) => `Giá tham khảo, kiểm tra lần cuối ${checkedAtIso}`,
  affiliateLabel: 'Link affiliate: chúng tôi có thể nhận hoa hồng nếu bạn mua qua link này.',
  notImplemented: (taskId: string) => `Chưa triển khai (xem ${taskId} trong UpComming_Plan)`,

  // Đăng nhập / đăng ký
  loginTitle: 'Đăng nhập',
  loginEmailLabel: 'Email',
  loginPasswordLabel: 'Mật khẩu',
  loginSubmit: 'Đăng nhập',
  signupSubmit: 'Tạo tài khoản',
  loginSwitchToSignup: 'Chưa có tài khoản? Tạo tài khoản',
  loginSwitchToLogin: 'Đã có tài khoản? Đăng nhập',
  logoutButton: 'Đăng xuất',

  // Tạo plan
  createPlanTitle: 'Tạo lộ trình học',
  createPlanPackageLabel: 'Chọn gói học',
  createPlanPackageCore: 'Bản gốc — 425 giờ (chỉ task bắt buộc)',
  createPlanPackageFull: 'Kèm phần bổ sung — 566 giờ (gồm cả task tùy chọn)',
  createPlanStartDateLabel: 'Ngày bắt đầu',
  createPlanHoursPerDayLabel: 'Số giờ học mỗi ngày học',
  createPlanDaysPerWeekLabel: 'Số ngày học mỗi tuần',
  createPlanTimezoneLabel: 'Múi giờ',
  createPlanSubmit: 'Tạo lộ trình',
  createPlanHoursDisclaimer: 'Số giờ ở trên là ước tính của tác giả, chưa kiểm chứng — dùng để tự lên lịch, không phải cam kết.',
  createPlanDoneUpToLabel: 'Mình đã học XONG đến hết task…',
  createPlanDoneUpToNone: 'Chưa bắt đầu (bắt đầu từ task đầu tiên)',

  // Hôm nay
  todayTitle: 'Hôm nay',
  todayDoneButton: 'Xong',
  todayEmptyState: 'Không còn task nào đang chờ — bạn đã hoàn thành lộ trình!',
  todayPhraseMatrixTitle: 'Xem toàn bộ theo nhóm (bấm để mở)',
  todayCarouselViewDetail: 'Xem chi tiết',
  todayFinishLabel: (date: string) => `Ngày dự kiến hoàn thành: ${date}`,
  todayRequiredHoursLabel: (hours: number) => `Cần khoảng ${hours} giờ/ngày để xong trong 365 ngày`,

  // Cập nhật tiến độ (đã học đến đâu)
  updateProgressTitle: 'Cập nhật tiến độ',
  updateProgressSelectLabel: 'Mình đã học XONG đến hết task…',
  updateProgressPreviewSubmit: 'Xem trước',
  updateProgressNextTaskLabel: (name: string) => `Task tiếp theo của bạn sẽ là: ${name}`,
  updateProgressAllDoneLabel: 'Bạn đã xong toàn bộ lộ trình!',
  updateProgressConfirmCount: (count: number) => `Sẽ đánh dấu ${count} task là Xong.`,
  updateProgressConfirmRange: (first: string, last: string) => `Từ "${first}" đến "${last}".`,
  updateProgressConfirmNone: 'Không có task nào cần đổi — có thể bạn đã đánh dấu xong tới đây rồi.',
  updateProgressConfirmSubmit: 'Xác nhận',
  updateProgressChooseAgain: 'Chọn lại',
  updateProgressResult: (count: number) => `Đã đánh dấu ${count} task là Xong.`,
  updateProgressLink: 'Cập nhật tiến độ (đã học đến đâu)',

  // Lộ trình
  roadmapTitle: 'Lộ trình',
  roadmapDoneCount: (done: number, total: number) => `${done}/${total} xong`,
  roadmapOptionalOffCount: (count: number) => `${count} task tùy chọn đang tắt`,
  progressRingDonePercent: 'hoàn thành',
  progressRingOuterHint: (total: number) => `Tổng ${total} task phải làm (đã bỏ task tùy chọn tắt).`,
  progressRingInnerHint: (done: number, total: number, pct: number) => `${done}/${total} task đã xong (${pct}%).`,
  progressStatsTitle: 'Thống kê theo milestone',
  progressStatsWriting: (n: number) => `${n} lần viết`,
  progressStatsSpeaking: (n: number) => `${n} phút nói`,
  roadmapJumpToCurrent: 'Đi tới task đang học',
  roadmapStatusTodo: 'Chưa làm',
  roadmapStatusInProgress: 'Đang làm',
  roadmapStatusDone: 'Đã xong',
  roadmapStatusSkipped: 'Đã bỏ qua',
  roadmapOptionalTag: '(tùy chọn)',
  roadmapNoDates: '—',
  roadmapEstHoursLabel: (hours: number) => `${hours} giờ`,

  // Trang chi tiết task
  taskDetailBackLink: '← Quay lại',
  taskDetailDeliverableLabel: 'Sản phẩm cần đạt',
  taskDetailToolNoteLabel: 'Công cụ/ghi chú',
  taskDetailWritingTargetLabel: (n: number) => `Mục tiêu: viết ${n} lần`,
  taskDetailStatsTitle: 'Ghi nhận của bạn',
  taskDetailWritingRepsLabel: 'Số lần đã viết',
  taskDetailSpeakingMinutesLabel: 'Số phút đã luyện nói',
  taskDetailKanaAccuracyLabel: 'Độ chính xác tự đánh giá (%, để trống nếu chưa rõ)',
  taskDetailStatsSubmit: 'Lưu ghi nhận',
  taskDetailStatsSaved: 'Đã lưu.',
  taskDetailPrevTask: '‹ Task trước',
  taskDetailNextTask: 'Task sau ›',
  taskDetailNotFound: 'Không tìm thấy task này trong lộ trình của bạn.',

  // Thao tác lịch (T-006)
  scheduleSkipButton: 'Bỏ qua',
  scheduleUnskipButton: 'Bỏ "bỏ qua"',
  scheduleReenableOptionalButton: 'Bật lại task tùy chọn này',
  scheduleReenableOptionalNote: 'Không ảnh hưởng tiến độ hiện tại — chỉ thêm 1 task chưa hoàn thành vào lộ trình.',
  scheduleMarkDoneButton: 'Đánh dấu đã xong',
  scheduleUnmarkDoneButton: 'Bỏ đánh dấu xong (quay lại làm mốc)',
  scheduleDelayLabel: 'Hoãn (số ngày)',
  scheduleDelaySubmit: 'Hoãn',
  schedulePinLabel: 'Ghim ngày bắt đầu',
  schedulePinSubmit: 'Ghim',
  scheduleUnpinSubmit: 'Xóa ghim',
  scheduleBreakTitle: 'Nghỉ N ngày',
  scheduleBreakFromLabel: 'Từ ngày',
  scheduleBreakDaysLabel: 'Số ngày nghỉ',
  scheduleBreakSubmit: 'Áp dụng nghỉ',
  scheduleActionSuccess: 'Đã cập nhật.',
  scheduleConflictWarning: 'Ngày ghim sớm hơn lịch tự tính nên có thể trùng với task trước.',
  scheduleClampedWarning: 'Ngày ghim đã ở quá khứ nên bị đưa về ngày bắt đầu hiệu lực (hôm nay).',
  scheduleNoTaskAffected: 'Không có task nào sau ngày này cần dời — không đổi gì.',

  // Cần mua (/buy) — T-007
  buyTitle: 'Cần mua',
  buyUrgencyOverdue: 'Quá hạn đặt',
  buyUrgencyDueSoon: 'Gần tới hạn',
  buyUrgencyUpcoming: 'Sắp tới',
  buyUrgencyLater: 'Chưa gấp',
  buyLateRiskWarning: 'Đã đặt nhưng ngày giao dự kiến muộn hơn ngày cần có — có thể trễ.',
  buyNeedByLabel: (date: string) => `Cần có: ${date}`,
  buyOrderByLabel: (date: string) => `Hạn đặt: ${date}`,
  buyFreeAlternativeLabel: (text: string) => `Miễn phí thay thế: ${text}`,
  buyStatusNone: 'Chưa mua',
  buyStatusOwned: 'Đã có',
  buyStatusOrdered: 'Đã đặt',
  buyStatusReceived: 'Đã nhận',
  buyStatusNotNeeded: 'Không cần',
  buyMarkOwned: 'Đã có',
  buyMarkOrdered: 'Đã đặt',
  buyMarkNotNeeded: 'Không cần',
  buyMarkReceived: 'Đã nhận',
  buyCancelOrder: 'Hủy, về chưa mua',
  buyEtaLabel: 'Ngày dự kiến giao',
  buyEtaSubmit: 'Lưu ngày giao',
  buyEditEta: 'Sửa ngày dự kiến giao',
  buyBuyButton: 'Mua',
  buyAffiliateNote: '(link affiliate)',
  buyOptionalSectionTitle: 'Tài nguyên tùy chọn',
  buyOptInToggle: 'Tôi muốn dùng',
  buyOptOutNote: 'Chưa bật — sẽ không nhắc mua.',
  buyMonthlySpendTitle: 'Tổng chi theo tháng',
  buyTotalsCore: (vnd: number) => `Cốt lõi: ${vnd.toLocaleString('vi-VN')}đ`,
  buyTotalsOptional: (vnd: number) => `Tùy chọn: ${vnd.toLocaleString('vi-VN')}đ`,
  buySpentSoFar: (vnd: number) => `Đã chi: ${vnd.toLocaleString('vi-VN')}đ`,
  buyRemaining: (vnd: number) => `Còn phải chi: ${vnd.toLocaleString('vi-VN')}đ`,
  buyActionSuccess: 'Đã cập nhật.',
  buyEmptyState: 'Không có mục nào cần mua ngay bây giờ.',

  // Sắp tới (/upcoming) — T-007
  upcomingTitle: 'Sắp tới',
  upcomingHorizonLabel: '14 ngày tới',
  upcomingTabAll: 'Tất cả',
  upcomingTabTask: 'Học',
  upcomingTabPurchase: 'Mua',
  upcomingEmptyState: 'Không có task hay mục cần mua nào trong 14 ngày tới.',
  upcomingTaskStartLabel: (date: string) => `Bắt đầu: ${date}`,
  upcomingPurchaseOrderByLabel: (date: string) => `Hạn đặt: ${date}`,

  // Điều hướng
  navUpcoming: 'Sắp tới',
  navBuy: 'Cần mua',

  // Chuông thông báo
  notificationBellLabel: 'Thông báo',
  notificationEmptyState: 'Chưa có thông báo nào.',
  notificationPanelTitle: 'Thông báo',
} as const;
